import { OnInit } from '@angular/core';
export declare class NgAppworks implements OnInit {
    AWAccelerometer: any;
    AWAppManager: any;
    AWAuth: any;
    AWCache: any;
    AWCalendar: any;
    AWCamera: any;
    AWCompass: any;
    AWComponent: any;
    AWContacts: any;
    AWDevice: any;
    AWFileChooser: any;
    AWFileSystem: any;
    AWFileTransfer: any;
    AWFinder: any;
    AWGlobalization: any;
    AWHeader: any;
    AWHeaderBar: any;
    AWKeyboard: any;
    AWLauncher: any;
    AWLocation: any;
    AWMedia: any;
    AWMediaCapture: any;
    AWMenu: any;
    AWMobileFileSystem: any;
    AWNotificationManager: any;
    AWOfflineManager: any;
    AWPage: any;
    AWPlugin: any;
    AWProxy: any;
    AWQRReader: any;
    AWScanner: any;
    AWSecureStorage: any;
    AWStorage: any;
    AWVibration: any;
    AWWebView: any;
    constructor();
    ngOnInit(): void;
}
